// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using whatappbot.infrastructure.Context;

#nullable disable

namespace whatappbot.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("whatappbot.domain.Entity.ChatUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WhatsAppId")
                        .IsUnique();

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("whatappbot.domain.Entity.ConversationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatUserId")
                        .HasColumnType("int");

                    b.Property<string>("DatosTemporales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaInteraccion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatUserId")
                        .IsUnique();

                    b.ToTable("ConversationStates");
                });

            modelBuilder.Entity("whatappbot.domain.Entity.ConversationState", b =>
                {
                    b.HasOne("whatappbot.domain.Entity.ChatUser", "ChatUser")
                        .WithOne("ConversationState")
                        .HasForeignKey("whatappbot.domain.Entity.ConversationState", "ChatUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatUser");
                });

            modelBuilder.Entity("whatappbot.domain.Entity.ChatUser", b =>
                {
                    b.Navigation("ConversationState");
                });
#pragma warning restore 612, 618
        }
    }
}
